[build-system]
requires = ["flit_core >= 3.2.0"]
build-backend = "flit_core.buildapi"

[project]
name = "streamlit-ldap-authenticator"
version = "0.3.1"
description = "Authenticate using ldap"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }
authors = [
    { name = "Nathan Chen", email = "nathan.chen.198@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
dependencies = [
    "streamlit >= 1.37",
    "python-ldap == 3.4.5",
    "pyjwt >= 2.8.0",
    "streamlit-cookies-controller >= 0.0.3",
    "streamlit-rsa-auth-ui >= 1.1.1"
]

[project.urls]
Homepage = "https://github.com/NathanChen198/streamlit-ldap-authenticator"

[dependency-groups]
dev = [
    "pyrefly>=0.60",
    "pytest>=9.0.0",
    "pytest-mock",
    "prek",
]

[tool.pytest]
testpaths = ["tests"]

[tool.uv]
override-dependencies = [
    "python-ldap == 3.4.5 ; sys_platform != 'win32'",
    "python-ldap @ https://github.com/cgohlke/python-ldap-build/releases/download/v3.4.5/python_ldap-3.4.5-cp314-cp314-win_amd64.whl ; sys_platform == 'win32' and python_version == '3.14'",
    "python-ldap @ https://github.com/cgohlke/python-ldap-build/releases/download/v3.4.5/python_ldap-3.4.5-cp313-cp313-win_amd64.whl ; sys_platform == 'win32' and python_version == '3.13'",
    "python-ldap @ https://github.com/cgohlke/python-ldap-build/releases/download/v3.4.5/python_ldap-3.4.5-cp312-cp312-win_amd64.whl ; sys_platform == 'win32' and python_version == '3.12'",
    "python-ldap @ https://github.com/cgohlke/python-ldap-build/releases/download/v3.4.5/python_ldap-3.4.5-cp311-cp311-win_amd64.whl ; sys_platform == 'win32' and python_version == '3.11'",
]
